#132: Update latest release
adoptium/obsolete---adoptium.net pull request #135
Opened 2021-08-02 16:18 UTC by jeffalder

##### Checklist

- [x] `npm test` passes
- [x] documentation is changed or added (if applicable)
- [x] permission has been obtained to add new logo (if applicable)
- [x] contribution guidelines followed [here](https://github.com/adoptium/adoptium.net/blob/master/CONTRIBUTING.md)

2021-08-02 16:24 UTC, jeffalder commented
![Screen Shot 2021-08-02 at 16 24 24](https://user-images.githubusercontent.com/49817386/127893376-f1b72470-bc71-4336-8335-34c3e4302feb.png)

2021-08-02 19:03 UTC, karianna requested changes
2 small changes

2021-08-02 19:03 UTC, karianna commented on src/handlebars/support.handlebars
> +              Sep 2021</strong>
Oct

2021-08-02 19:03 UTC, karianna commented on src/handlebars/support.handlebars
> +              Sep 2021</strong>
Oct

2021-08-03 10:13 UTC, karianna approved these changes

2021-08-03 10:21 UTC, merged

2021-08-03 15:53 UTC, jeffalder commented
@karianna Sorry for not turning the changes around quickly enough!

2021-08-03 17:18 UTC, karianna commented
Oh not at all - we're all volunteers here and I was just trying to avoid having to use my less than stellar git skills as I had a potentially clashing PR :-)