Put JRE-equivalent jlink command in the site banner
adoptium/obsolete---adoptium.net pull request #188
Opened 2021-10-01 09:46 UTC by sxa

Adding all TSC members as reviewers FAO since Slack isn't behaving today due to a DNS TTL issue so it's harder to discuss on there at the moment.

I was thinking that in the short term at least - even if just until we update the banner for the October releases - putting the cut & pastable one liner on the main adoptium page (initially as a banner, maybe somewhere else alongside the downloads later) might be a good idea. I feel it's a bit better than [shipping a new tool](https://github.com/adoptium/temurin-build/pull/2736) with our JDKs  (which pretty much just runs the one liner) which we have to support and would have to carefully consider if we wanted to change the options on it. Plus even if we do ship the tool this would give us a quick way of getting the information directly in front of people on our front page.

The interesting observation on this is that the footprint of disk of a jlink'd version with this comment is smaller thand the "JRE" we used to produce, but the `lib/modules` file does NOT compress as well as the one in the JRE for some reason and so when you tar it up it seems to be larger than the "legacy JRE" package.

_(Side comment: This may also have been an opportunity to promote jlink.online, but that currently seems to be down and only displays an AdoptOpenJDK logo)_

Signed-off-by: Stewart X Addison <sxa@redhat.com>

##### Checklist

- [x] `npm test` passes
- [x] documentation is changed or added (if applicable)
- [ ] permission has been obtained to add new logo (if applicable)
- [x] contribution guidelines followed [here](https://github.com/adoptium/adoptium.net/blob/master/CONTRIBUTING.md)

2021-10-01 10:02 UTC, gdams commented on src/handlebars/partials/header.handlebars
> +    <strong>1st October 2021</strong> Eclipse Temurin 17 GA now available. Missing the v17 JRE? Try taking our JDK and run:<br/>
```suggestion
    <strong>1st October 2021</strong> Eclipse Temurin 17 GA now available. Missing the v17 JRE? Try downloading our JDK and run:<br/>
```

2021-10-01 10:02 UTC, gdams commented on src/handlebars/partials/header.handlebars
> +    <strong>1st October 2021</strong> Eclipse Temurin 17 GA now available. Missing the v17 JRE? Try taking our JDK and run:<br/>
just a suggestion but taking seems a bit slangly here

2021-10-01 10:23 UTC, tellison commented
IMHO I don't like putting code on the homepage like this. jlink and friends is for developers, we don't lead with that stuff for all users. I'd much prefer we _remove_ more technical things (like version choices) from the homepage than add them.

2021-10-01 10:28 UTC, karianna requested changes
I think the banner should point to a blog post or doc with a fuller explanation.

2021-10-01 10:29 UTC, sxa commented on src/handlebars/partials/header.handlebars
> +    <strong>1st October 2021</strong> Eclipse Temurin 17 GA now available. Missing the v17 JRE? Try taking our JDK and run:<br/>
Agreed :-)

2021-10-01 10:38 UTC, sxa commented
> IMHO I don't like putting code on the homepage like this. jlink and friends is for developers, we don't lead with that stuff for all users. I'd much prefer we _remove_ more technical things (like version choices) from the homepage than add them.

I would normally agree, but as a "hot topic" at the moment with near daily comments it might be worth having it there for a short period, especially since it's a disconnect from earlier versions and it feels important to get the message across during this period.

> I think the banner should point to a blog post or doc with a fuller explanation.

It could link to the [FAQ question](https://adoptium.net/faq.html#jres) for now (Although I haven't currently added the `jlink` command into the FAQ - was thinking about that this morning too and it's probably worth a separate PR regardless to do that. We also have the info in the [blog post about docker](https://blog.adoptium.net/2021/08/using-jlink-in-dockerfiles/) which I've pointed people towards a few times to say "Hey we've considered this, and this is an option" although it has a slightly different set of modules in the example (only `java.base`). I think it would be good to have an article outside the FAQ that decouples the JRE issue from Docker though.

I'm happy to look at putitng such a blog post together that we can link to unless someone else is particuarly keen to do it. I will say that it would be nice to try and cover what's different between the "legacy JREs" and a jlinked one.

2021-10-01 10:40 UTC, karianna commented
+1 to a separate blog post and even an FAQ item as well.  Very happy to help!

2021-10-01 10:53 UTC, karianna commented
Also see https://github.com/adoptium/containers/issues/77

2021-10-01 12:09 UTC, jerboaa reviewed
I concur. We should write this up as a blog post and then it can be linked from the banner if it's needed.

2021-10-01 21:00 UTC, sxa commented
I was travelling earlier today but have now put a blog post draft at https://github.com/adoptium/blog.adoptium.net/pull/99. Once we're ok with the content we can add a link from the banner and/or FAQ.

2021-10-04 10:49 UTC, sxa commented
Moving back to draft for now as this will likely be implemented as [blog post](https://github.com/adoptium/blog.adoptium.net/pull/99) + [banner linking to it](https://github.com/adoptium/adoptium.net/pull/189)

2021-10-08 15:53 UTC, closed without merging