Update supported platforms page to be more user friendly
adoptium/obsolete---adoptium.net pull request #197
Opened 2021-10-06 15:31 UTC by gdams

##### Checklist

- [ ] `npm test` passes
- [ ] documentation is changed or added (if applicable)
- [ ] permission has been obtained to add new logo (if applicable)
- [ ] contribution guidelines followed [here](https://github.com/adoptium/adoptium.net/blob/master/CONTRIBUTING.md)

2021-10-06 15:35 UTC, karianna requested changes
whitespace changes otherwise good.

2021-10-06 15:35 UTC, karianna commented on src/handlebars/supported_platforms.handlebars
> +  <h3>This section lists the operating systems that are supported with the latest release of Eclipse Temurin.</h3>
indenting please

2021-10-06 15:44 UTC, gdams commented on src/handlebars/supported_platforms.handlebars
> +  <h3>This section lists the operating systems that are supported with the latest release of Eclipse Temurin.</h3>
just pushed a commit

2021-10-07 08:10 UTC, gdams commented
Dumping my thoughts here so I don't forget.

Centos is no longer on s390x (it's ClefOS)

We should likely support SLES on s390x

2021-10-07 19:26 UTC, karianna approved these changes
LGTM

2021-10-13 13:23 UTC, gdams commented
**Suggestions from PMC**

centos/rhel check on arm32

remove centos7 arm64

remove ClefOS for s390x

add glibc and macos 10.12 footnote

add Solaris update version (10u11)

Alpine Linux (clarify that it's headless)

2021-10-13 14:11 UTC, sxa requested changes
Can we update the footnotes to include the `libc` versions for the other Linux versions as well i.e. 2.23 on arm32, 2.17 elsewhere. Although since the Linux/arm32 one presumably works on CentOS7 we could just specify 2.17 for all non-x64 ones, but I'm a little surprised it runs ok :-) We do no testing on that.

2021-10-13 16:08 UTC, gdams commented
> Can we update the footnotes to include the libc versions for the other Linux versions as well i.e. 2.23 on arm32, 2.17 elsewhere. Although since the Linux/arm32 one presumably works on CentOS7 we could just specify 2.17 for all non-x64 ones, but I'm a little surprised it runs ok :-) We do no testing on that.

Updated

2021-10-13 16:15 UTC, sxa approved these changes
LGTM now. We should definitely look to add SLES back in at least for Linux/s390x when we get a machine stood up for that, but the current table is good and looks vastly better than the old one. Thanks.

2021-10-13 16:19 UTC, merged