Add page for JDK Mission Control downloads
adoptium/obsolete---adoptium.net pull request #247
Opened 2021-12-09 21:07 UTC by jiekang

This PR adds a page with downloads for the Adoptium builds of JDK Mission Control. It is a copy of the contents [here](https://github.com/AdoptOpenJDK/openjdk-website/blob/master/src/handlebars/jmc.handlebars) updated with the latest 8.1.1 release. It is accessible under a Projects submenu, similar to the older AdoptOpenJDK site.

##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed [here](https://github.com/adoptium/adoptium.net/blob/master/CONTRIBUTING.md)

2021-12-10 10:13 UTC, jerboaa requested changes
All links should point to an Adoptium release repo. E.g.
https://github.com/adoptium/jmc-overrides/releases

2021-12-10 10:13 UTC, jerboaa commented on src/handlebars/jmc.handlebars
> +          <a href="https://github.com/AdoptOpenJDK/openjdk-jmc-overrides/releases/download/8.1.1/org.openjdk.jmc-8.1.1-win32.win32.x86_64.zip">org.openjdk.jmc-8.1.1-win32.win32.x86_64.zip</a>
These are pointing to `AdoptOpenJDK`. That's a no-go for Adoptium. They'd have to point to an `Adoptium` release repo.

2021-12-10 11:33 UTC, karianna requested changes

2021-12-10 11:33 UTC, karianna commented on src/handlebars/jmc.handlebars
> +<h1 class="margin-bottom large-title">JDK Mission Control</h1>
I think there's an actual [Eclipse Mission Control](https://projects.eclipse.org/projects/adoptium.mc#:~:text=Eclipse%20Mission%20Control%20enables%20you%20to%20monitor%20and,dynamic%20optimization%20of%20the%20Java%20Virtual%20Machine%20%28JVM%29.) Project? If so we should be branding it as such.  So "Eclipse Mission Control"

CC @thegreystone who might know more about the status here

2021-12-10 13:38 UTC, jiekang commented on src/handlebars/jmc.handlebars
> +          <a href="https://github.com/AdoptOpenJDK/openjdk-jmc-overrides/releases/download/8.1.1/org.openjdk.jmc-8.1.1-win32.win32.x86_64.zip">org.openjdk.jmc-8.1.1-win32.win32.x86_64.zip</a>
Ah, right; changed to point to github.com/adoptium/jmc-overrides. Thanks!

2021-12-10 13:40 UTC, jiekang commented on src/handlebars/jmc.handlebars
> +<h1 class="margin-bottom large-title">JDK Mission Control</h1>
Okay, makes sense. Updated to Eclipse Mission Control and will await response on status before resolving.

2021-12-10 18:28 UTC, jerboaa approved these changes

2021-12-10 21:42 UTC, karianna approved these changes

2021-12-10 21:43 UTC, karianna commented
I'd like to make sure the @thegreystone is happy with this landing - rest looks great though thanks!

2021-12-12 21:22 UTC, thegreystone commented
Looks good! I'd change "For a Eclipse Mission Control introduction" to "For an introduction to Mission Control".

2021-12-13 10:04 UTC, gdams commented on src/handlebars/partials/menu.handlebars
> +          <li><a href="./jmc.html">JDK Mission Control</a></li>
```suggestion
          <li><a href="./jmc.html">Eclipse Mission Control</a></li>
```

2021-12-13 11:54 UTC, merged